import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type User = {
    uid: string;
    name: string;
    email: string;
    role: string;
    disabled?: boolean;
    disabledReason?: string;
    branch?: string;
    admissionYear?: number;
};

type ItemRow = {
    id: string;
    title?: string;
    category?: string;
    status?: string;
    reportedBy?: string;
    lastSeenLocation?: string;
    foundLocation?: string;
    createdAt?: any;
};

type ClaimRow = {
    id: string;
    status?: string;
    itemTitle?: string;
    itemType?: string;
    claimantEmail?: string;
    location?: string;
    createdAt?: any;
    verifiedAt?: any;
    assignedMaintainerName?: string;
};

type LogRow = {
    id: string;
    action: string;
    actorUid?: string;
    targetUid?: string;
    message?: string;
    createdAt?: any;
};

function fmt(v: any) {
    try {
        if (!v) return "";
        if (v?.toDate) return v.toDate().toLocaleString();
        if (typeof v === "string") return new Date(v).toLocaleString();
        return "";
    } catch {
        return "";
    }
}

export function generateAdminPdfReport(args: {
    generatedBy: { name?: string; email?: string };
    users: User[];
    lostItems: ItemRow[];
    foundItems: ItemRow[];
    claims: ClaimRow[];
    logs: LogRow[];
}) {
    const { generatedBy, users, lostItems, foundItems, claims, logs } = args;

    const doc = new jsPDF({ unit: "pt", format: "a4" });

    const now = new Date();
    const dateStr = now.toLocaleString();

    // Title
    doc.setFontSize(16);
    doc.text("Lost & Found — Admin Activity Report", 40, 50);

    doc.setFontSize(10);
    doc.text(`Generated: ${dateStr}`, 40, 70);
    doc.text(`Generated by: ${generatedBy.name || "-"} (${generatedBy.email || "-"})`, 40, 85);

    // Summary
    const totalLost = lostItems.length;
    const totalFound = foundItems.length;
    const pending = claims.filter((c) => c.status === "pending").length;
    const approved = claims.filter((c) => c.status === "approved").length;
    const rejected = claims.filter((c) => c.status === "rejected").length;

    autoTable(doc, {
        startY: 105,
        head: [["Summary", "Value"]],
        body: [
            ["Users", String(users.length)],
            ["Lost items", String(totalLost)],
            ["Found items", String(totalFound)],
            ["Claims - Pending", String(pending)],
            ["Claims - Approved", String(approved)],
            ["Claims - Rejected", String(rejected)],
            ["Logs", String(logs.length)],
        ],
        styles: { fontSize: 9 },
        headStyles: { fillColor: [20, 20, 20] },
    });

    // Users table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 18,
        head: [["Name", "Email", "Role", "Status", "Branch", "Year"]],
        body: users.map((u) => [
            u.name || "",
            u.email || "",
            (u.role || "").toUpperCase(),
            u.disabled ? `DISABLED${u.disabledReason ? ` (${u.disabledReason})` : ""}` : "ACTIVE",
            u.branch || "",
            u.admissionYear ? String(u.admissionYear) : "",
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [20, 20, 20] },
        columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 140 } },
    });

    // Lost items table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 18,
        head: [["Title", "Category", "Status", "Location", "ReportedBy", "CreatedAt"]],
        body: lostItems.map((i) => [
            i.title || "",
            i.category || "",
            i.status || "",
            i.lastSeenLocation || "",
            i.reportedBy || "",
            fmt(i.createdAt),
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [20, 20, 20] },
    });

    // Found items table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 18,
        head: [["Title", "Category", "Status", "Location", "ReportedBy", "CreatedAt"]],
        body: foundItems.map((i) => [
            i.title || "",
            i.category || "",
            i.status || "",
            i.foundLocation || "",
            i.reportedBy || "",
            fmt(i.createdAt),
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [20, 20, 20] },
    });

    // Claims table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 18,
        head: [["Item", "Type", "Status", "Claimant", "Assigned Office", "CreatedAt", "VerifiedAt"]],
        body: claims.map((c) => [
            c.itemTitle || "",
            (c.itemType || "").toUpperCase(),
            (c.status || "").toUpperCase(),
            c.claimantEmail || "",
            c.assignedMaintainerName || "",
            fmt(c.createdAt),
            fmt(c.verifiedAt),
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [20, 20, 20] },
    });

    // Logs table (limit big logs to avoid huge pdf)
    const logsLimited = logs.slice(0, 300);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 18,
        head: [["Action", "Message", "Actor", "Target", "Time"]],
        body: logsLimited.map((l) => [
            l.action || "",
            (l.message || "").slice(0, 120),
            l.actorUid || "",
            l.targetUid || "",
            fmt(l.createdAt),
        ]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [20, 20, 20] },
    });

    const filename = `lost-and-found-report-${now.toISOString().slice(0, 10)}.pdf`;
    doc.save(filename);
}
